compat: include byteswap.h instead of endian.h
This fixes the following compile error on systems using musl libc:

net_io.c: In function 'bam32ToDouble':
net_io.c:1412:32: error: implicit declaration of function '__bswap_32'; did you mean '__bswap32'? [-Werror=implicit-function-declaration]
 1412 |     return (double) ((int32_t) __bswap_32(bam) * 8.38190317153931E-08);
      |                                ^~~~~~~~~~
      |                                __bswap32
net_io.c: In function 'decodeHulcMessage':
net_io.c:1440:40: error: implicit declaration of function '__bswap_16'; did you mean '__bswap16'? [-Werror=implicit-function-declaration]
 1440 |         Modes.receiver.antenna_flags = __bswap_16(hsm.status.flags);
      |                                        ^~~~~~~~~~
      |                                        __bswap16

Compile-tested on both glibc and musl systems.

Signed-off-by: Stijn Tintel <stijn@linux-ipv6.be>