readsbrrd: fix compilation with GCC 14
Due to stricter defaults in GCC 14, readsb compile fails with the
following errors in readsbrrd.c:

readsbrrd.c: In function ‘rrd_create_files’:
readsbrrd.c:219:46: error: passing argument 2 of ‘rrd_create’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  219 |         rrd.status = rrd_create(rrd.argc, rrd.argv);
      |                                           ~~~^~~~~
      |                                              |
      |                                              char **
In file included from readsbrrd.h:29,
                 from readsbrrd.c:20:
/usr/include/rrd.h:158:5: note: expected ‘const char **’ but argument is of type ‘char **’
  158 |     const char **);
      |     ^~~~~~~~~~~~~
readsbrrd.c: In function ‘rrd_update_file’:
readsbrrd.c:249:42: error: passing argument 2 of ‘rrd_update’ from incompatible pointer type [-Werror=incompatible-pointer-types]
  249 |     rrd.status = rrd_update(rrd.argc, rrd.argv);
      |                                       ~~~^~~~~
      |                                          |
      |                                          char **
/usr/include/rrd.h:179:5: note: expected ‘const char **’ but argument is of type ‘char **’
  179 |     const char **);
      |     ^~~~~~~~~~~~~

Signed-off-by: Stijn Tintel <stijn@linux-ipv6.be>